name: AI Code Review

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - dev

jobs:
  review:
    uses: dev-five-git/action/.github/workflows/ai-code-review.yml@main
    secrets: inherit
